version: '3'

services:
  mangoose-console:
     image: emcmongoose/mongoose-console
     ports:
     - "${MONGOOSE_PORT}"
  grafana:
     image: grafana/grafana
     ports:
     - "${GRAFANA_PORT}"
  prometheus:
    image: prom/prometheus
    ports:
    - "${PROMETHEUS_PORT}"

