version: '3'

services:
  mongoose-console:
    image: emcmongoose/mongoose-console:${CONSOLE_VER}
    ports:
    - "${CONSOLE_PORT}:${CONSOLE_PORT}"
    env_file:
    - .env
  grafana:
    image: grafana/grafana:${GRAFANA_VER}
    ports:
    - "${GRAFANA_PORT}:${GRAFANA_PORT}"
  prometheus:
    image: prom/prometheus:${PROMETHEUS_VER}
    ports:
    - "${PROMETHEUS_PORT}:${PROMETHEUS_PORT}"
