version: '3'

services:
  mangoose-console:
    build: ./
    volumes:
      - /src/main/webapp
    ports:
      - 5001:80
  grafana:
     image: grafana/grafana
  prometheus:
    image: prom/prometheus
