version: '3'

services:
  mangoose-console:
    image: emcmongoose/mongoose-console:${MONGOOSE_VER}
    ports:
    - "8080:${NGINX_PORT}"
  grafana:
    image: grafana/grafana:${GRAFANA_VER}
    ports:
    - "${GRAFANA_PORT}:${GRAFANA_PORT}"
  prometheus:
    image: prom/prometheus:${PROMETHEUS_VER}
    ports:
    - "${PROMETHEUS_PORT}:${PROMETHEUS_PORT}"

